-- 1.
SELECT L.LOCATION_ID, COUNT(D.DEPARTMENT_ID) AS NUM_DEPARTMENTS
FROM LOCATIONS L
LEFT JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
WHERE D.DEPARTMENT_ID IS NOT NULL
GROUP BY L.LOCATION_ID;

-- 2.
SELECT L.LOCATION_ID, COUNT(D.DEPARTMENT_ID) AS NUM_DEPARTMENTS
FROM LOCATIONS L
LEFT JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
GROUP BY L.LOCATION_ID;

-- 3.
SELECT L.LOCATION_ID, COUNT(D.DEPARTMENT_ID) AS NUM_DEPARTMENTS
FROM LOCATIONS L
LEFT JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
GROUP BY L.LOCATION_ID
HAVING COUNT(D.DEPARTMENT_ID) > 1;

-- 4.
SELECT D.DEPARTMENT_NAME, D.LOCATION_ID, COUNT(E.EMPLOYEE_ID) AS NUM_EMPLOYEES, 
       SUM(E.SALARY) AS TOTAL_SALARY, AVG(E.SALARY) AS AVG_SALARY
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME, D.LOCATION_ID
ORDER BY D.LOCATION_ID ASC, AVG(E.SALARY) DESC;

-- 5.
SELECT D.DEPARTMENT_NAME, D.LOCATION_ID, COUNT(E.EMPLOYEE_ID) AS NUM_EMPLOYEES,
       SUM(E.SALARY) AS TOTAL_SALARY, AVG(E.SALARY) AS AVG_SALARY
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME, D.LOCATION_ID
UNION ALL
SELECT 'NO DEPARTMENT' AS DEPARTMENT_NAME, NULL AS LOCATION_ID, 
       COUNT(E.EMPLOYEE_ID) AS NUM_EMPLOYEES, SUM(E.SALARY) AS TOTAL_SALARY, 
       AVG(E.SALARY) AS AVG_SALARY
FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID IS NULL;
